[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/img/small/:name"
  to = "https://upbeat-kilby-9bc84c.netlify.com/img/:name?nf=resize&w=100"
  status = 302


